
name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    
    steps:
    - uses: actions/checkout@v3
    - run: docker-compose -f docker-compose-build.yaml build --parallel
    - run: docker tag udagram-frontend:local thomas1y/udagram-frontend
    - run: docker tag udagram-api-feed thomas1y/udagram-api-feed
    - run: docker tag udagram-api-user thomas1y/udagram-api-user
    - run: docker tag reverseproxy thomas1y/reverseproxy
    - run: echo "${{secrets.DOCKER_PASSWORD}}" | docker login -u "${{secrets.DOCKER_USERNAME}}" --password-stdin
    - run: docker push thomas1y/udagram-frontend
    - run: docker push thomas1y/udagram-api-feed
    - run: docker push thomas1y/udagram-api-user
    - run: docker push thomas1y/reverseproxy
